spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: usermanagement
    password: root
    hikari:
      minimumIdle: 1
      maximumPoolSize: 20
      idleTimeout: 30000
      connectionTimeout: 40000
      maxLifetime: 900000
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 30000000
      refresh-token:
        expiration: 30000000

